---
language: ruby
env:
  global:
    - CC_TEST_REPORTER_ID=3f7916c75017fb71b3753488bc2e038fba1ad4574c6d1d4f9702566d7ba6a285
cache: bundler
rvm:
  - 2.7.1
before_install: gem install bundler -v 2.1.4
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
